Add uci
AaltoML/t-SVGP pull request #7
Opened 2021-11-07 16:01 UTC by edchangy11

- Added the uci data and two scripts that that in a dataset input and will reproduce the figure in the paper.
- Not sure if we want to keep the same file structure now for where the data is stored.

2021-11-07 16:36 UTC, thevincentadam requested changes

2021-11-07 16:36 UTC, thevincentadam commented on docs/figures/uci_classification.py
> +    m_cvi = t_SVGP(
cvi

2021-11-07 16:36 UTC, thevincentadam commented on docs/figures/uci_classification.py
> +    gpflow.set_trainable(m_cvi.lambda_1 , False)
cvi

2021-11-07 16:36 UTC, thevincentadam commented on docs/figures/uci_classification.py
> +    models.append(m_cvi)
same

2021-11-07 17:15 UTC, edchangy11 commented on docs/figures/uci_classification.py
> +    models.append(m_cvi)
changed

2021-11-07 18:56 UTC, thevincentadam commented
Late reply sorry,
I still think it would be best to move the experiments in a dedicated folder, with the data and associated utils.

Definitely, I'd separate the utils that are data loading utilities from the actual method utils.
And my reasoning is that the notebooks are more proof of concept / illustrations than experiments here.

Let me know your thoughts

2021-11-08 10:25 UTC, thevincentadam approved these changes

2021-11-08 10:26 UTC, merged